{
 "title": "Backend Metrics",
 "tags": [
  "sre-app",
  "backend"
 ],
 "refresh": "10s",
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(requests_total)", "legendFormat": "Total Requests" }
   ]
  },
  {
   "title": "Requests by Endpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (requests_by_endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(errors_total)", "legendFormat": "Total Errors" }
   ]
  },
  {
   "title": "Errors by Status Code",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (code) (errors_by_status_code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Average Response Time (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "avg(response_time_avg)", "legendFormat": "Avg Response Time" }
   ]
  },
  {
   "title": "Uptime (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "max(uptime_seconds)", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "megabytes" } },
   "targets": [
    { "expr": "avg(memory_usage_mb)", "legendFormat": "Memory Usage" }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "avg(cpu_percent)", "legendFormat": "CPU Usage" }
   ]
  },
  { "title": "Application Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "App Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "app_info",
     "legendFormat": "Worker: {{worker_id}}, Storage: {{storage}}"
    }
   ]
  }
 ]
}