global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Our Flask backend with Redis-backed metrics
  - job_name: 'flask-backend'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

#   # Kubernetes service discovery (when running in k8s)
#   - job_name: 'kubernetes-services'
#     kubernetes_sd_configs:
#       - role: service
#     relabel_configs:
#       # Only scrape services with the prometheus=true label
#       - source_labels: [__meta_kubernetes_service_label_prometheus]
#         action: keep
#         regex: true
      
#       # Use service name as instance name
#       - source_labels: [__meta_kubernetes_service_name]
#         target_label: instance
      
#       # Add namespace label
#       - source_labels: [__meta_kubernetes_namespace]
#         target_label: kubernetes_namespace
      
#       # Use named port for metrics
#       - source_labels: [__meta_kubernetes_service_port_name]
#         action: keep
#         regex: metrics

#   # Kubernetes pods (alternative service discovery)
#   - job_name: 'kubernetes-pods'
#     kubernetes_sd_configs:
#       - role: pod
#     relabel_configs:
#       # Only scrape pods with prometheus.io/scrape=true annotation
#       - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
#         action: keep
#         regex: true
      
#       # Use custom path if specified
#       - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
#         action: replace
#         target_label: __metrics_path__
#         regex: (.+)
      
#       # Use custom port if specified
#       - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
#         action: replace
#         regex: ([^:]+)(?::\d+)?;(\d+)
#         replacement: $1:$2
#         target_label: __address__
      
#       # Add pod labels
#       - action: labelmap
#         regex: __meta_kubernetes_pod_label_(.+)
      
#       # Add namespace
#       - source_labels: [__meta_kubernetes_namespace]
#         action: replace
#         target_label: kubernetes_namespace
      
#       # Add pod name
#       - source_labels: [__meta_kubernetes_pod_name]
#         action: replace
#         target_label: kubernetes_pod_name

#   # Node Exporter (system metrics - install separately)
#   - job_name: 'node-exporter'
#     static_configs:
#       - targets: ['localhost:9100']  # If running node_exporter locally

# # Alerting configuration
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - "alertmanager:9093"  # Uncomment when you add Alertmanager

# # Storage configuration
# # storage:
# #   tsdb:
# #     retention.time: 30d  # Keep metrics for 30 days
